fix: Update 'main' property in package.json
Update the 'main' property in package.json to specify 'gitaclue.js' instead of the
default 'index.js'. This resolves the post-NPM issue where the message
"Error: Cannot find module 'gitaclue'" is issued from the statement
"const gitaclue = require('gitaclue/gitaclue');" in user programs

Resolves: N/a
See also: N/a